"use client";

import {
  useActionState,
  useMemo,
  useState,
} from "react";

import {
  saveProviderMapping,
  type ProviderMappingActionState,
} from "@/app/admin/products/actions";


type ProviderOption = {
  id: string;
  name: string;
};


type ExistingMapping = {
  id: string;

  providerId: string;

  externalProductId: string;

  productUrl:
    | string
    | null;

  affiliateUrl:
    | string
    | null;

  price:
    | string
    | null;

  currency:
    | string
    | null;

  availability:
    | string
    | null;

  priority: number;

  syncStatus: string;
};


type ProviderKind =
  | "amazon"
  | "walmart"
  | "generic";


function getProviderKind(
  providerName:
    | string
    | undefined
): ProviderKind {

  const normalized =
    providerName
      ?.trim()
      .toLowerCase() ??
    "";


  if (
    normalized.includes(
      "amazon"
    )
  ) {
    return "amazon";
  }


  if (
    normalized.includes(
      "walmart"
    )
  ) {
    return "walmart";
  }


  return "generic";
}


function getExternalIdLabel(
  kind: ProviderKind
) {

  if (
    kind ===
    "amazon"
  ) {
    return "Amazon ASIN";
  }


  if (
    kind ===
    "walmart"
  ) {
    return "Walmart item ID";
  }


  return "External Product ID";
}


function getExternalIdPlaceholder(
  kind: ProviderKind
) {

  if (
    kind ===
    "amazon"
  ) {
    return "Example: B0XXXXXXXX";
  }


  if (
    kind ===
    "walmart"
  ) {
    return "Walmart item / product ID";
  }


  return "Provider product ID / SKU";
}


function getProviderDescription(
  kind: ProviderKind
) {

  if (
    kind ===
    "amazon"
  ) {
    return (
      <>
        Manual Amazon Associates mapping.
        Enter the product ASIN and the
        affiliate link generated by your
        Amazon Associates account. The
        Creators API can be connected later
        without changing the Venuvella
        product.
      </>
    );
  }


  if (
    kind ===
    "walmart"
  ) {
    return (
      <>
        Manual Walmart affiliate mapping.
        Enter the Walmart item ID and the
        affiliate tracking URL supplied by
        Walmart or its affiliate platform.
        Automated data feeds can be connected
        later.
      </>
    );
  }


  return (
    <>
      Manual provider mapping. Enter the
      merchant&apos;s external product ID and
      affiliate destination.
    </>
  );
}


export function ProviderMappingForm({
  productId,
  providers,
  mapping,
}: {
  productId: string;

  providers: ProviderOption[];

  mapping?: ExistingMapping;
}) {

  const editing =
    Boolean(mapping);


  const initialProviderId =
    mapping?.providerId ??
    providers[0]?.id ??
    "";


  const [
    selectedProviderId,
    setSelectedProviderId,
  ] = useState(
    initialProviderId
  );


  const selectedProvider =
    useMemo(
      () =>
        providers.find(
          (provider) =>
            provider.id ===
            selectedProviderId
        ),
      [
        providers,
        selectedProviderId,
      ]
    );


  const providerKind =
    getProviderKind(
      selectedProvider?.name
    );


  const initialState:
    ProviderMappingActionState = {
      ok: false,
      message: "",
    };


  const [
    state,
    action,
    pending,
  ] = useActionState(
    saveProviderMapping,
    initialState
  );


  const requiresAffiliateUrl =
    providerKind ===
      "amazon" ||
    providerKind ===
      "walmart";


  return (
    <form
      action={action}
      className="grid gap-5"
    >

      <input
        type="hidden"
        name="productId"
        value={productId}
      />


      {mapping && (
        <input
          type="hidden"
          name="mappingId"
          value={mapping.id}
        />
      )}


      {/* PROVIDER */}

      <div>

        <label
          htmlFor={`provider-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          Provider
        </label>


        <select
          id={`provider-${mapping?.id ?? "new"}`}
          name="providerId"
          value={
            selectedProviderId
          }
          onChange={(
            event
          ) =>
            setSelectedProviderId(
              event.target.value
            )
          }
          className="admin-input"
          required
        >

          {providers.map(
            (provider) => (

              <option
                key={
                  provider.id
                }
                value={
                  provider.id
                }
              >
                {
                  provider.name
                }
              </option>

            )
          )}

        </select>

      </div>


      {/* PROVIDER MODE */}

      <div className="rounded-xl border border-[var(--line)] bg-[#f4f3ee] p-4">

        <div className="flex flex-wrap items-center gap-2">

          <span className="rounded-full border border-[var(--line)] bg-white px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.12em]">
            Manual affiliate
          </span>


          {providerKind ===
            "amazon" && (

            <span className="rounded-full border border-[var(--line)] bg-white px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.12em]">
              Amazon Associates
            </span>

          )}


          {providerKind ===
            "walmart" && (

            <span className="rounded-full border border-[var(--line)] bg-white px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.12em]">
              Walmart Affiliate
            </span>

          )}

        </div>


        <p className="mt-3 text-xs leading-5 text-[var(--muted)]">
          {
            getProviderDescription(
              providerKind
            )
          }
        </p>

      </div>


      {/* EXTERNAL PRODUCT ID */}

      <div>

        <label
          htmlFor={`external-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          {
            getExternalIdLabel(
              providerKind
            )
          }
        </label>


        <input
          id={`external-${mapping?.id ?? "new"}`}
          name="externalProductId"
          defaultValue={
            mapping?.externalProductId ??
            ""
          }
          className="admin-input"
          placeholder={
            getExternalIdPlaceholder(
              providerKind
            )
          }
          autoCapitalize={
            providerKind ===
            "amazon"
              ? "characters"
              : undefined
          }
          required
        />


        {providerKind ===
          "amazon" && (

          <p className="mt-2 text-xs text-[var(--muted)]">
            Amazon ASINs contain 10 letters
            and/or numbers. Venuvella will
            normalize the ASIN to uppercase.
          </p>

        )}


        {providerKind ===
          "walmart" && (

          <p className="mt-2 text-xs text-[var(--muted)]">
            Use the Walmart item or product ID
            belonging to the exact product
            destination.
          </p>

        )}

      </div>


      {/* PRODUCT URL */}

      <div>

        <label
          htmlFor={`product-url-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          Original product URL
        </label>


        <input
          id={`product-url-${mapping?.id ?? "new"}`}
          name="productUrl"
          type="url"
          defaultValue={
            mapping?.productUrl ??
            ""
          }
          className="admin-input"
          placeholder={
            providerKind ===
            "amazon"
              ? "https://www.amazon.com/dp/ASIN"
              : providerKind ===
                  "walmart"
                ? "https://www.walmart.com/ip/..."
                : "https://..."
          }
        />


        <p className="mt-2 text-xs text-[var(--muted)]">
          Optional. This is the normal merchant
          product page, not necessarily the
          monetized affiliate link.
        </p>

      </div>


      {/* AFFILIATE URL */}

      <div>

        <label
          htmlFor={`affiliate-url-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          Affiliate URL
        </label>


        <input
          id={`affiliate-url-${mapping?.id ?? "new"}`}
          name="affiliateUrl"
          type="url"
          defaultValue={
            mapping?.affiliateUrl ??
            ""
          }
          className="admin-input"
          placeholder={
            providerKind ===
            "amazon"
              ? "Paste your Amazon Associates link"
              : providerKind ===
                  "walmart"
                ? "Paste your Walmart affiliate tracking link"
                : "https://..."
          }
          required={
            requiresAffiliateUrl
          }
        />


        <p className="mt-2 text-xs leading-5 text-[var(--muted)]">

          {providerKind ===
            "amazon" && (
            <>
              Generate this link from your
              Amazon Associates account.
              Venuvella will send visitors to
              this destination through its
              internal /go/ redirect.
            </>
          )}


          {providerKind ===
            "walmart" && (
            <>
              Use the monetized tracking URL
              provided through your Walmart
              affiliate account or approved
              affiliate platform.
            </>
          )}


          {providerKind ===
            "generic" && (
            <>
              Use the merchant&apos;s approved
              affiliate tracking destination.
            </>
          )}

        </p>

      </div>


      {/* PRICE / CURRENCY */}

      <div className="grid gap-5 md:grid-cols-2">

        <div>

          <label
            htmlFor={`price-${mapping?.id ?? "new"}`}
            className="admin-label"
          >
            Manual price
          </label>


          <input
            id={`price-${mapping?.id ?? "new"}`}
            name="price"
            type="number"
            step="0.01"
            min="0"
            defaultValue={
              mapping?.price ??
              ""
            }
            className="admin-input"
            placeholder="0.00"
          />


          <p className="mt-2 text-xs text-[var(--muted)]">
            Optional. Update manually while API
            or feed synchronization is not
            available.
          </p>

        </div>


        <div>

          <label
            htmlFor={`currency-${mapping?.id ?? "new"}`}
            className="admin-label"
          >
            Currency
          </label>


          <input
            id={`currency-${mapping?.id ?? "new"}`}
            name="currency"
            maxLength={3}
            defaultValue={
              mapping?.currency ??
              "USD"
            }
            className="admin-input uppercase"
            placeholder="USD"
          />


          <p className="mt-2 text-xs text-[var(--muted)]">
            Use the ISO currency code.
          </p>

        </div>

      </div>


      {/* AVAILABILITY */}

      <div>

        <label
          htmlFor={`availability-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          Manual availability
        </label>


        <input
          id={`availability-${mapping?.id ?? "new"}`}
          name="availability"
          defaultValue={
            mapping?.availability ??
            ""
          }
          className="admin-input"
          placeholder="In stock"
        />


        <p className="mt-2 text-xs text-[var(--muted)]">
          Optional manual snapshot. Examples:
          In stock, Limited availability,
          Temporarily unavailable.
        </p>

      </div>


      {/* PRIORITY */}

      <div>

        <label
          htmlFor={`priority-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          Provider priority
        </label>


        <input
          id={`priority-${mapping?.id ?? "new"}`}
          name="priority"
          type="number"
          min="0"
          max="9999"
          step="1"
          defaultValue={
            mapping?.priority ??
            100
          }
          className="admin-input"
          required
        />


        <p className="mt-2 text-xs leading-5 text-[var(--muted)]">
          Lower numbers are preferred by
          Venuvella. For example, priority 10
          is preferred before priority 20.
          This lets you choose which merchant
          receives traffic first when multiple
          providers sell the same product.
        </p>

      </div>


      {/* STATUS */}

      <div>

        <label
          htmlFor={`sync-status-${mapping?.id ?? "new"}`}
          className="admin-label"
        >
          Mapping status
        </label>


        <select
          id={`sync-status-${mapping?.id ?? "new"}`}
          name="syncStatus"
          defaultValue={
            mapping?.syncStatus ??
            "SUCCESS"
          }
          className="admin-input"
        >

          <option value="SUCCESS">
            Ready / Active
          </option>

          <option value="PENDING">
            Pending review
          </option>

          <option value="STALE">
            Needs manual update
          </option>

          <option value="FAILED">
            Invalid / Failed
          </option>

        </select>


        <p className="mt-2 text-xs leading-5 text-[var(--muted)]">
          For a verified manual affiliate link,
          use Ready / Active. If the price,
          availability or affiliate destination
          needs to be checked, use Needs manual
          update.
        </p>

      </div>


      {/* RESULT */}

      {state.message && (

        <div
          className={
            state.ok
              ? "admin-success"
              : "admin-error"
          }
        >
          {
            state.message
          }
        </div>

      )}


      {/* SAVE */}

      <div className="flex justify-end">

        <button
          type="submit"
          disabled={pending}
          className="admin-primary"
        >

          {pending
            ? "Saving…"
            : editing
              ? "Save changes"
              : "Add affiliate mapping"}

        </button>

      </div>

    </form>
  );
}